modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "hold_w_to_ponder"
version = "${version}"
displayName = "Hold W to Ponder"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
logoFile = "icon.png"

[[dependencies.hold_w_to_ponder]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hold_w_to_ponder]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.hold_w_to_ponder]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"
